


name: paddle-build-linux
on: 
  push:
    paths: 
      - '.github/workflows/paddle-build-linux.yml'

env:
  PADDLE_VERSION: "3.1.0"
  PADDLE_BRANCH: "v3.1.0"

jobs:
  build-all:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # - { os: windows-2022, name: win_cu129_cudnn99_sm120, cuda: 12.9.0, cudnn: 9.9.0.52,python: "3.10", cmake_flags: "-DWITH_GPU=ON -DWITH_SHARED_PHI=ON -DCUDA_ARCH_NAME=Manual -DON_INFER=ON -DCUDA_ARCH_BIN=120 -DWITH_UNITY_BUILD=ON" }
          - { os: ubuntu-24.04, name: cu129_cudnn910_sm120, cuda: 12.9.0, cudnn: 9.9.0.52,python: "3.10", cmake_flags: "-DWITH_GPU=ON -DWITH_SHARED_PHI=ON -DCUDA_ARCH_NAME=Manual -DCUDNN_ROOT=/usr/local/cuda-12.9 -DON_INFER=ON -DCUDA_ARCH_BIN=120 -DWITH_UNITY_BUILD=ON" }
    steps:
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}


    - name: Install 
      shell: bash
      run: |
        pip install numpy protobuf wheel ninja
        wget --no-verbose https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2404/x86_64/cuda-ubuntu2404.pin
        sudo mv cuda-ubuntu2404.pin /etc/apt/preferences.d/cuda-repository-pin-600
        wget --no-verbose https://developer.download.nvidia.com/compute/cuda/12.9.1/local_installers/cuda-repo-ubuntu2404-12-9-local_12.9.1-575.57.08-1_amd64.deb
        sudo dpkg -i cuda-repo-ubuntu2404-12-9-local_12.9.1-575.57.08-1_amd64.deb
        sudo cp /var/cuda-repo-ubuntu2404-12-9-local/cuda-*-keyring.gpg /usr/share/keyrings/
        sudo apt-get update
        sudo apt-get -y install cuda-toolkit-12-9

        wget --no-verbose https://developer.download.nvidia.com/compute/cudnn/9.9.0/local_installers/cudnn-local-repo-ubuntu2404-9.9.0_1.0-1_amd64.deb
        sudo dpkg -i cudnn-local-repo-ubuntu2404-9.9.0_1.0-1_amd64.deb
        sudo cp /var/cudnn-local-repo-ubuntu2404-9.9.0/cudnn-*-keyring.gpg /usr/share/keyrings/
        sudo apt-get update
        sudo apt-get -y install cudnn

    - name: Checkout Paddle repo
      uses: actions/checkout@v4
      with:
        repository: PaddlePaddle/Paddle
        ref: "release/3.1"
        path: paddle-src

    # - name: Apply patches
    #   shell: pwsh
    #   run: |
    #     cd ./paddle-src
    #     Invoke-WebRequest -Uri https://raw.githubusercontent.com/sdcb/PaddleSharp/refs/heads/feature/3.1/build/capi.patch -OutFile capi.patch
    #     git apply --ignore-whitespace capi.patch
    #     rm capi.patch

    - name: Configure with CMake
      shell: pwsh
      run: |
        pip install -r ./paddle-src/python/requirements.txt
        mkdir ./paddle-src/build
        mkdir ./paddle-src/build/paddle/phi/ops/yaml/inconsistent
        mkdir ./paddle-src/build/paddle/phi/ops/yaml/legacy

        cd ./paddle-src/build
        cmake .. -GNinja ${{ matrix.cmake_flags }}

    - name: Build with Ninja
      run: |
        cd ./paddle-src/build
        ninja all

    # - name: Show build files
    #   shell: bash
    #   run: |
    #     ls -lR ./paddle-src/build

    - name: Upload paddle_whl
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.name }}
        path: ./paddle-src/build/python/dist/*
